package code.vipul.aoc2019;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * https://adventofcode.com/2019/day/6
 */
public class Solve6 {

    private static String input = "21X)BWV\n" +
            "YZJ)YLQ\n" +
            "FQS)PZW\n" +
            "R64)71F\n" +
            "ZH4)QVZ\n" +
            "LWB)H4Q\n" +
            "4HQ)PVJ\n" +
            "TZ5)VBV\n" +
            "LF1)FKZ\n" +
            "GKS)BGN\n" +
            "45B)2NS\n" +
            "14W)2JY\n" +
            "1XY)FJ8\n" +
            "ZRC)WR9\n" +
            "GCL)6PB\n" +
            "LP4)GQ8\n" +
            "26V)HTK\n" +
            "3M8)1GJ\n" +
            "47Q)JYK\n" +
            "WDB)N2R\n" +
            "KH8)TGY\n" +
            "LFX)N2X\n" +
            "VSZ)7PC\n" +
            "M6W)4WL\n" +
            "HH9)8PC\n" +
            "L59)8Y8\n" +
            "Q49)LWH\n" +
            "CJ5)XDG\n" +
            "K51)FGH\n" +
            "H31)2RJ\n" +
            "39M)Y4M\n" +
            "12C)VLF\n" +
            "PZW)7DW\n" +
            "MP2)19Q\n" +
            "R76)CHH\n" +
            "N6J)KBW\n" +
            "WR9)W25\n" +
            "T99)ZF1\n" +
            "1TS)8SM\n" +
            "8WW)YX7\n" +
            "PW6)B2J\n" +
            "7KX)YM5\n" +
            "HM6)GVX\n" +
            "DNB)2YP\n" +
            "6WC)2LW\n" +
            "BG5)SB6\n" +
            "KK1)JTF\n" +
            "YDT)244\n" +
            "GGQ)2DJ\n" +
            "GCP)Q8H\n" +
            "S1Y)J69\n" +
            "LBV)DYG\n" +
            "ZKN)JBS\n" +
            "8XY)Y8Z\n" +
            "XMH)NHD\n" +
            "XVM)2LX\n" +
            "SYP)BC8\n" +
            "PXH)YYG\n" +
            "F29)G9Y\n" +
            "BYX)4QS\n" +
            "8MY)S1D\n" +
            "N2Y)BZK\n" +
            "FRC)72W\n" +
            "S2K)YH5\n" +
            "7JF)K65\n" +
            "DJ9)K4L\n" +
            "P26)WXT\n" +
            "DW9)1DJ\n" +
            "NP4)3SB\n" +
            "XS7)CDL\n" +
            "6XH)4ZT\n" +
            "2DJ)GCP\n" +
            "2K4)VV1\n" +
            "Q6P)NNN\n" +
            "HQW)ZR9\n" +
            "9G2)FNB\n" +
            "H9N)5ZJ\n" +
            "13Z)GKD\n" +
            "9MW)37Y\n" +
            "VDY)BG9\n" +
            "BL3)12C\n" +
            "LNN)JST\n" +
            "Z3V)T39\n" +
            "XS3)WYG\n" +
            "8J5)QFQ\n" +
            "7DW)DXY\n" +
            "JMV)DM4\n" +
            "VL3)V7Q\n" +
            "GZC)ZHV\n" +
            "3N6)R2H\n" +
            "FQ6)7LG\n" +
            "SR9)D66\n" +
            "1M8)K2L\n" +
            "24N)M94\n" +
            "JST)WM9\n" +
            "7SB)99Q\n" +
            "58J)YN7\n" +
            "WWH)5KS\n" +
            "C39)X9J\n" +
            "58S)KBP\n" +
            "TVF)VNG\n" +
            "TKC)Y34\n" +
            "KKP)4S6\n" +
            "XSP)939\n" +
            "N6J)DZP\n" +
            "JXP)N6R\n" +
            "KNJ)7FS\n" +
            "N3V)LMJ\n" +
            "JVF)R94\n" +
            "21C)R4Z\n" +
            "NYK)5GN\n" +
            "GVJ)Q6C\n" +
            "R69)NRS\n" +
            "GLS)C7D\n" +
            "T4J)46R\n" +
            "5GB)51S\n" +
            "9WD)7PN\n" +
            "HHX)KK2\n" +
            "H2P)ZML\n" +
            "DWD)Q9F\n" +
            "FKZ)LC3\n" +
            "Q9F)M8N\n" +
            "CRZ)LM1\n" +
            "6DP)YML\n" +
            "NSR)L2X\n" +
            "PMX)Q7K\n" +
            "37R)1GF\n" +
            "L4G)P4W\n" +
            "17N)X6D\n" +
            "JTF)89B\n" +
            "JGJ)DVJ\n" +
            "VF9)GMW\n" +
            "NHD)DJ3\n" +
            "TRY)F6S\n" +
            "J11)BVW\n" +
            "95X)XB5\n" +
            "3XD)HPM\n" +
            "7BB)1LW\n" +
            "FJ8)TV4\n" +
            "JV3)M9W\n" +
            "T7L)6SS\n" +
            "R48)LSB\n" +
            "F2P)9D2\n" +
            "PTY)QBY\n" +
            "KXM)6G1\n" +
            "N1H)Q2R\n" +
            "P27)SR9\n" +
            "1S2)N3G\n" +
            "V7Q)642\n" +
            "891)TW7\n" +
            "B9Y)BRL\n" +
            "GW4)3XZ\n" +
            "QWM)G46\n" +
            "WVK)S6N\n" +
            "N82)317\n" +
            "8PG)S21\n" +
            "NT3)1VX\n" +
            "QB5)Y3H\n" +
            "PTT)639\n" +
            "G8M)WM8\n" +
            "B36)LX9\n" +
            "M9M)4P3\n" +
            "3F9)Q3R\n" +
            "DND)TJL\n" +
            "VQB)6N3\n" +
            "PJT)JTK\n" +
            "BBN)T4L\n" +
            "LYP)M3V\n" +
            "T9R)HH9\n" +
            "XBR)3X5\n" +
            "MX3)SWF\n" +
            "SF1)MXT\n" +
            "X67)6DQ\n" +
            "82Z)FQ4\n" +
            "L64)FNG\n" +
            "CDG)5D9\n" +
            "JKZ)XZ5\n" +
            "MH1)1KD\n" +
            "5NW)ZH4\n" +
            "P3T)76Z\n" +
            "2M4)CKW\n" +
            "54L)8P7\n" +
            "JSH)5H5\n" +
            "LGR)P2V\n" +
            "QNV)SJ7\n" +
            "KPS)XMQ\n" +
            "F2H)49M\n" +
            "8NJ)KKP\n" +
            "XZ1)LRZ\n" +
            "RVK)J5Z\n" +
            "QT9)NGQ\n" +
            "1TK)P7X\n" +
            "39M)595\n" +
            "DN9)HKY\n" +
            "HK1)ZRH\n" +
            "SH1)JV5\n" +
            "B25)GQ6\n" +
            "QZC)WYC\n" +
            "6CJ)F5D\n" +
            "5R1)HQ7\n" +
            "FNT)P4J\n" +
            "4R6)P49\n" +
            "LG4)QT9\n" +
            "GWH)RY1\n" +
            "1FX)ZK8\n" +
            "HK4)G2N\n" +
            "4WL)GPR\n" +
            "SQT)KK1\n" +
            "RT4)FCN\n" +
            "NRF)P84\n" +
            "DQW)4L4\n" +
            "52N)T4J\n" +
            "69D)2FV\n" +
            "RMV)J7N\n" +
            "S9J)1WM\n" +
            "B88)9GT\n" +
            "5M7)GXN\n" +
            "3XF)6FX\n" +
            "FL9)8VZ\n" +
            "X88)JZR\n" +
            "ZVZ)8J2\n" +
            "Q83)94V\n" +
            "82Y)HT7\n" +
            "7Y7)7X3\n" +
            "KNK)R1W\n" +
            "469)PMG\n" +
            "D9Z)GD1\n" +
            "Z62)WR1\n" +
            "YDF)6B6\n" +
            "5KS)6GW\n" +
            "57T)ML7\n" +
            "GXC)R89\n" +
            "S2N)99C\n" +
            "JFH)RP9\n" +
            "KPH)R26\n" +
            "DZX)93P\n" +
            "CWT)C2H\n" +
            "VKN)5M7\n" +
            "VNG)SH1\n" +
            "G2N)F6Q\n" +
            "NFV)FK3\n" +
            "R65)TQL\n" +
            "Z6T)4NG\n" +
            "RQN)KPR\n" +
            "972)9TB\n" +
            "KZ1)6TY\n" +
            "8K2)HKL\n" +
            "KHJ)H1W\n" +
            "6N3)XTR\n" +
            "25Q)T49\n" +
            "8HF)K9M\n" +
            "GQX)PHP\n" +
            "5ZJ)9S7\n" +
            "C7D)VMJ\n" +
            "JXV)SJD\n" +
            "J17)64C\n" +
            "5XN)WN7\n" +
            "PH9)WQH\n" +
            "43T)Q9V\n" +
            "Z5F)NZ8\n" +
            "VHQ)D95\n" +
            "244)7KX\n" +
            "6N7)JPH\n" +
            "HC8)HND\n" +
            "ZF1)39F\n" +
            "24X)ZPF\n" +
            "BWV)HQW\n" +
            "R3N)5R1\n" +
            "QB9)6XY\n" +
            "KHW)KFZ\n" +
            "S2V)DRQ\n" +
            "S21)1RQ\n" +
            "C9V)TSD\n" +
            "Q1Y)LC2\n" +
            "93Y)W5C\n" +
            "8ST)T4P\n" +
            "R5Z)CL4\n" +
            "424)WNZ\n" +
            "R7M)5JS\n" +
            "4R6)H97\n" +
            "ZXZ)S62\n" +
            "FRH)SBJ\n" +
            "ZK8)N82\n" +
            "6FX)MTK\n" +
            "Z5M)BRQ\n" +
            "YYP)FX8\n" +
            "RZJ)DRK\n" +
            "V8G)TKQ\n" +
            "5L9)J1G\n" +
            "RZG)69H\n" +
            "R9G)X79\n" +
            "WFS)ZJQ\n" +
            "4P8)GXC\n" +
            "TYW)S54\n" +
            "R2H)QH7\n" +
            "6HX)F2H\n" +
            "BBD)DC5\n" +
            "DDB)6WC\n" +
            "2G3)4JN\n" +
            "FKC)K7V\n" +
            "XTK)8BD\n" +
            "Z7X)QGY\n" +
            "8CG)3F9\n" +
            "F39)MM9\n" +
            "F1L)1R7\n" +
            "ZVH)JDC\n" +
            "BVW)PXM\n" +
            "PRV)BF7\n" +
            "FX8)1XR\n" +
            "FB2)XN6\n" +
            "R9L)Z1V\n" +
            "YDT)H52\n" +
            "6Z5)XZ1\n" +
            "QD2)Z7Y\n" +
            "TLS)6T3\n" +
            "54C)DL7\n" +
            "KPR)4TY\n" +
            "19N)415\n" +
            "1QG)GNN\n" +
            "S6N)4MK\n" +
            "4L8)LD2\n" +
            "5Z7)PRY\n" +
            "5C4)2MC\n" +
            "94B)DY3\n" +
            "CVK)GTS\n" +
            "7N7)P27\n" +
            "5MW)GGH\n" +
            "2HQ)JYL\n" +
            "L9J)HLP\n" +
            "5Y4)NGN\n" +
            "2BZ)GWN\n" +
            "HD8)CZS\n" +
            "HQ7)M9D\n" +
            "DC5)RK6\n" +
            "66W)2VT\n" +
            "3D4)GHZ\n" +
            "T49)VTP\n" +
            "PL4)ZS9\n" +
            "SJ7)TRC\n" +
            "NKT)G5Y\n" +
            "K1G)3GN\n" +
            "37V)4LG\n" +
            "KWL)VDZ\n" +
            "7XF)1P8\n" +
            "64C)FX4\n" +
            "DY4)J3F\n" +
            "RV8)8KF\n" +
            "DRQ)KQ7\n" +
            "HND)2N7\n" +
            "HQS)HMW\n" +
            "J24)9VX\n" +
            "7DK)3PM\n" +
            "467)VBK\n" +
            "Q6C)TZC\n" +
            "SZY)9TC\n" +
            "BMM)4S4\n" +
            "HFH)2S6\n" +
            "K5K)4QP\n" +
            "N6W)RZG\n" +
            "TKQ)489\n" +
            "4R1)F22\n" +
            "J1G)YDF\n" +
            "FVW)9WD\n" +
            "CV7)TMC\n" +
            "R6K)H31\n" +
            "GDL)X14\n" +
            "H1B)NKT\n" +
            "XTR)PL6\n" +
            "BSC)SM7\n" +
            "MLT)S7B\n" +
            "22S)R7T\n" +
            "X8Y)4WX\n" +
            "NR9)NK9\n" +
            "FSM)J3S\n" +
            "WHF)VSG\n" +
            "ZBG)Q3D\n" +
            "RMY)7KM\n" +
            "XBX)1M8\n" +
            "MHY)1C2\n" +
            "GSS)X9G\n" +
            "86F)Y4W\n" +
            "VL6)6H9\n" +
            "1VH)L3B\n" +
            "SF8)CDG\n" +
            "GTK)45F\n" +
            "49M)NLL\n" +
            "FN6)PN3\n" +
            "KSC)R3Z\n" +
            "6TN)3QN\n" +
            "FNG)742\n" +
            "X45)WWH\n" +
            "SF5)2WH\n" +
            "JSJ)B1H\n" +
            "95L)M8F\n" +
            "L59)C4Y\n" +
            "93P)M89\n" +
            "K1C)6ZZ\n" +
            "21T)8M6\n" +
            "X9M)7NX\n" +
            "WPK)LNG\n" +
            "393)F6N\n" +
            "M4L)JXP\n" +
            "VKN)X88\n" +
            "NFK)ZVZ\n" +
            "LKV)C2V\n" +
            "SWX)TM8\n" +
            "V7F)8ZN\n" +
            "3RW)FD8\n" +
            "9SM)H27\n" +
            "TP3)1YB\n" +
            "6MG)D8X\n" +
            "8S7)345\n" +
            "9SV)X67\n" +
            "25P)JDD\n" +
            "BFX)TNG\n" +
            "36J)VBH\n" +
            "HN7)WVK\n" +
            "ZR3)3NR\n" +
            "M3V)GPY\n" +
            "52M)MFV\n" +
            "MZB)CJ5\n" +
            "MX3)XLQ\n" +
            "LCG)PHS\n" +
            "HZD)RNC\n" +
            "GWN)DWD\n" +
            "XBM)WP4\n" +
            "2FV)YXW\n" +
            "ZTP)QD2\n" +
            "R1G)JY6\n" +
            "KY4)8CG\n" +
            "H54)RVK\n" +
            "5HG)WYQ\n" +
            "BVC)SK1\n" +
            "948)P3T\n" +
            "SV8)5MW\n" +
            "V4D)YLT\n" +
            "69X)LNZ\n" +
            "BL3)Y97\n" +
            "DXG)WLZ\n" +
            "VV1)SS3\n" +
            "ZCD)VXB\n" +
            "X6D)XL2\n" +
            "B9H)2NB\n" +
            "KHK)WPK\n" +
            "YLT)KFT\n" +
            "P49)CC5\n" +
            "KBW)CRH\n" +
            "8KQ)LJ4\n" +
            "8JJ)VTJ\n" +
            "TKM)428\n" +
            "3SB)273\n" +
            "GPY)R2Z\n" +
            "WTX)P6W\n" +
            "LB1)3PR\n" +
            "Y1R)DJM\n" +
            "25P)CY5\n" +
            "SVB)PJM\n" +
            "56N)S2V\n" +
            "H82)8D5\n" +
            "CYB)GP4\n" +
            "HJ2)BSH\n" +
            "2J1)F1T\n" +
            "C4Y)PRM\n" +
            "TZC)PM5\n" +
            "K55)NBJ\n" +
            "X43)LPP\n" +
            "WYG)3FW\n" +
            "WFG)N2Y\n" +
            "Q37)5L9\n" +
            "WSF)KSH\n" +
            "V2H)S9J\n" +
            "HN2)DW9\n" +
            "3LL)PFH\n" +
            "6X3)XVM\n" +
            "8XZ)991\n" +
            "26L)WTX\n" +
            "Y97)5C5\n" +
            "XXL)79Y\n" +
            "NK9)RR8\n" +
            "L7W)83Q\n" +
            "8TX)45B\n" +
            "GMJ)1H4\n" +
            "ZRW)58J\n" +
            "36X)PRS\n" +
            "8B2)HTL\n" +
            "8JZ)L94\n" +
            "PRY)QTW\n" +
            "PL4)X8Y\n" +
            "89N)1RJ\n" +
            "DFJ)62K\n" +
            "5QZ)CN3\n" +
            "RYQ)SL6\n" +
            "1H4)PGZ\n" +
            "B1H)J88\n" +
            "JCC)111\n" +
            "V6W)GG7\n" +
            "BZK)97X\n" +
            "49J)WVY\n" +
            "1WM)21X\n" +
            "TCN)KSC\n" +
            "RRD)26V\n" +
            "VC6)WPS\n" +
            "Y5S)YJS\n" +
            "DVR)2J8\n" +
            "LJF)839\n" +
            "64D)GZC\n" +
            "79Y)SZY\n" +
            "JHT)D6J\n" +
            "K4K)L59\n" +
            "YHB)QWM\n" +
            "6H9)MRR\n" +
            "X79)M62\n" +
            "LW7)GGB\n" +
            "469)TRQ\n" +
            "14K)951\n" +
            "L9Y)K51\n" +
            "W7C)Y73\n" +
            "XD1)CYL\n" +
            "1XQ)HYK\n" +
            "Q19)PWG\n" +
            "F4M)KHW\n" +
            "SM1)J3Q\n" +
            "MV1)1X9\n" +
            "NMV)3SM\n" +
            "8ZD)L61\n" +
            "VWX)6R6\n" +
            "S4Z)JK4\n" +
            "9GT)R13\n" +
            "F66)89X\n" +
            "DLT)K6R\n" +
            "H4C)NW9\n" +
            "R3D)6Z5\n" +
            "MKN)M5V\n" +
            "H4C)22S\n" +
            "BFM)J2V\n" +
            "KQW)G8D\n" +
            "V61)6HG\n" +
            "JX4)LH3\n" +
            "PHS)P68\n" +
            "V9M)56X\n" +
            "1Q6)Y8V\n" +
            "319)KX2\n" +
            "M8F)881\n" +
            "974)KSL\n" +
            "LRP)XXL\n" +
            "M3Y)Q39\n" +
            "LC3)B9H\n" +
            "4T8)ZRW\n" +
            "KYB)T7L\n" +
            "DXJ)72V\n" +
            "SRP)D3M\n" +
            "BRN)NGD\n" +
            "43S)NJ1\n" +
            "KWJ)VGZ\n" +
            "DNY)F2J\n" +
            "DKW)YT1\n" +
            "6B4)6N5\n" +
            "GRQ)RYT\n" +
            "4KV)WFG\n" +
            "6PG)T9R\n" +
            "Q3T)V2P\n" +
            "4M5)HLG\n" +
            "WKZ)9ZP\n" +
            "XTP)JMC\n" +
            "PVZ)JN1\n" +
            "5F2)26L\n" +
            "76Z)R5P\n" +
            "FVW)NS1\n" +
            "MWS)PXD\n" +
            "Z7Z)8S7\n" +
            "CTH)7C2\n" +
            "837)48K\n" +
            "3SM)HYY\n" +
            "J2B)1TS\n" +
            "Y8V)BS6\n" +
            "YYD)3XH\n" +
            "4F7)BFM\n" +
            "6S1)95D\n" +
            "4KN)JV3\n" +
            "GSZ)HVF\n" +
            "9CP)GPZ\n" +
            "BFN)LB1\n" +
            "N72)741\n" +
            "K6R)3WF\n" +
            "P4J)QQW\n" +
            "54G)469\n" +
            "36T)GJ4\n" +
            "HXM)X6W\n" +
            "MR9)M29\n" +
            "XMQ)SP9\n" +
            "71F)TJR\n" +
            "95X)DLT\n" +
            "1ZX)QVK\n" +
            "F1L)1SY\n" +
            "B7X)XDB\n" +
            "FJW)ZCR\n" +
            "43X)1XH\n" +
            "D5H)93V\n" +
            "FQH)5RJ\n" +
            "CLW)1RG\n" +
            "X4Y)X9M\n" +
            "CRH)DWH\n" +
            "XWX)GWZ\n" +
            "36J)TKC\n" +
            "YFN)YJ6\n" +
            "15X)MBT\n" +
            "6T3)NDG\n" +
            "8SY)4R7\n" +
            "XMG)HR5\n" +
            "KSZ)WKZ\n" +
            "PM5)3K8\n" +
            "BR4)J1T\n" +
            "F72)GV7\n" +
            "317)P1W\n" +
            "CV7)SPK\n" +
            "H53)PMX\n" +
            "NDG)56N\n" +
            "N68)ZXZ\n" +
            "X3W)XGJ\n" +
            "JRJ)S7X\n" +
            "MKN)DBW\n" +
            "8CM)953\n" +
            "M2K)3XL\n" +
            "95K)95X\n" +
            "58S)4HL\n" +
            "D95)L9Y\n" +
            "FRH)KQW\n" +
            "NLL)C3D\n" +
            "X1H)FM1\n" +
            "R1M)GGQ\n" +
            "Y8Z)W1B\n" +
            "KLD)G1V\n" +
            "6CJ)R5X\n" +
            "5C5)HN7\n" +
            "T7M)ZXT\n" +
            "SZF)B5W\n" +
            "RPW)6TG\n" +
            "3VP)2W9\n" +
            "X2J)RXH\n" +
            "DWG)C9V\n" +
            "9FB)524\n" +
            "1PZ)8ZD\n" +
            "ZKZ)6S1\n" +
            "L36)ZKN\n" +
            "F1J)2D4\n" +
            "LWC)6SW\n" +
            "SWF)Y4V\n" +
            "51L)MWS\n" +
            "KFZ)52N\n" +
            "GD1)HFH\n" +
            "LFK)L36\n" +
            "KPZ)ZQ6\n" +
            "3NT)W48\n" +
            "2CD)G3D\n" +
            "345)JXV\n" +
            "2LW)SWX\n" +
            "9ZY)XTJ\n" +
            "VWR)576\n" +
            "STH)NHY\n" +
            "L4X)M4L\n" +
            "ZML)RN7\n" +
            "RDF)7PB\n" +
            "7FK)3KR\n" +
            "GVX)DCF\n" +
            "1WX)DD2\n" +
            "971)H6W\n" +
            "H6H)BPX\n" +
            "BWQ)Z4J\n" +
            "JPL)3SV\n" +
            "QWJ)TR8\n" +
            "376)H9P\n" +
            "Q3D)1YS\n" +
            "1N2)FQ6\n" +
            "2LM)53K\n" +
            "VSG)6DP\n" +
            "KNM)8B7\n" +
            "S7B)YXF\n" +
            "YHB)JHP\n" +
            "Y7N)CPB\n" +
            "M29)3FB\n" +
            "J37)C8B\n" +
            "MK3)WHL\n" +
            "MRG)TQ8\n" +
            "BFM)DLH\n" +
            "H4Q)9HF\n" +
            "D81)R7M\n" +
            "LRQ)ZKZ\n" +
            "C1B)413\n" +
            "BKC)PW6\n" +
            "GP4)6MX\n" +
            "C39)JSH\n" +
            "BW8)TL2\n" +
            "71Q)3YP\n" +
            "415)H2V\n" +
            "DBH)BR4\n" +
            "JJ7)J2H\n" +
            "G52)87N\n" +
            "YV2)JN3\n" +
            "7PR)Z3V\n" +
            "999)G8M\n" +
            "S7Y)JRJ\n" +
            "G3D)88H\n" +
            "SR3)NTR\n" +
            "JY5)FC8\n" +
            "MYL)B7X\n" +
            "K7V)HM6\n" +
            "FXY)L47\n" +
            "NNN)GYH\n" +
            "8JJ)Y5S\n" +
            "3G5)37V\n" +
            "FLP)4B2\n" +
            "839)83S\n" +
            "H27)CV7\n" +
            "X4F)RXV\n" +
            "S3P)WMZ\n" +
            "LD2)SF8\n" +
            "DYG)77S\n" +
            "LGR)2LM\n" +
            "7BX)G2K\n" +
            "KNF)9S5\n" +
            "JBS)R45\n" +
            "T6C)CGH\n" +
            "CNV)2BZ\n" +
            "356)1KP\n" +
            "P93)54J\n" +
            "VGZ)31Y\n" +
            "GNG)HDL\n" +
            "RHW)222\n" +
            "4T4)4T8\n" +
            "WVY)M5Z\n" +
            "KQ7)XMG\n" +
            "K7F)S2N\n" +
            "X6Z)Z9S\n" +
            "XYH)WFC\n" +
            "7BM)J2B\n" +
            "H9F)LKV\n" +
            "WDJ)HWH\n" +
            "MWM)83M\n" +
            "YM5)7J5\n" +
            "Z62)8NR\n" +
            "99Q)TVF\n" +
            "VDP)C2N\n" +
            "9VX)B5T\n" +
            "YS6)KNF\n" +
            "35R)ZH5\n" +
            "JN5)Y4H\n" +
            "MSN)XSP\n" +
            "776)CJ4\n" +
            "3FB)HXT\n" +
            "HZV)6HY\n" +
            "Q6N)HXS\n" +
            "MBT)FTN\n" +
            "3JP)YJ2\n" +
            "4DC)KSD\n" +
            "8PG)5QZ\n" +
            "YSP)CNV\n" +
            "THM)CST\n" +
            "3X5)BPC\n" +
            "ZG9)4KY\n" +
            "8M6)MZ5\n" +
            "FDF)XNB\n" +
            "H4X)N72\n" +
            "ZH5)J79\n" +
            "KN7)ZXV\n" +
            "1GP)R76\n" +
            "K5R)CLZ\n" +
            "W8G)XVF\n" +
            "YJQ)HB8\n" +
            "BWC)TB6\n" +
            "WFH)T6C\n" +
            "DPB)VYF\n" +
            "K8N)KWJ\n" +
            "C2V)HMF\n" +
            "H93)HF3\n" +
            "TR8)MFW\n" +
            "RJ4)F66\n" +
            "BS6)FVW\n" +
            "QFW)5B2\n" +
            "ML7)FB2\n" +
            "TGY)X9Z\n" +
            "PRM)ZV3\n" +
            "4YX)4YV\n" +
            "36D)N6X\n" +
            "XLQ)TLS\n" +
            "WMZ)NRF\n" +
            "BCM)2CV\n" +
            "M74)CHT\n" +
            "JYL)LQ4\n" +
            "RSN)KXR\n" +
            "KNK)3Y2\n" +
            "89X)BJK\n" +
            "C2H)4YQ\n" +
            "YYQ)VMB\n" +
            "164)11H\n" +
            "WYQ)WSF\n" +
            "1RG)DRH\n" +
            "GKD)LLT\n" +
            "H53)T2F\n" +
            "X2Q)F82\n" +
            "B5D)5F8\n" +
            "JK1)4F7\n" +
            "1YB)P26\n" +
            "B6F)552\n" +
            "RTD)883\n" +
            "ZPF)DWG\n" +
            "JRV)DL1\n" +
            "MLQ)S1Y\n" +
            "TX8)5QV\n" +
            "NDT)2MF\n" +
            "HFS)61F\n" +
            "HD8)TCN\n" +
            "8BL)F2X\n" +
            "4MK)R6Z\n" +
            "WVN)RMY\n" +
            "GGX)JCC\n" +
            "GQ8)J11\n" +
            "H4V)5FJ\n" +
            "3JD)VNC\n" +
            "7KS)9SM\n" +
            "NTR)YV2\n" +
            "4LG)JK1\n" +
            "3XZ)GGX\n" +
            "SVZ)P96\n" +
            "4WG)N3V\n" +
            "QY7)8N9\n" +
            "XMP)LKL\n" +
            "T4P)RLM\n" +
            "J7C)JJZ\n" +
            "7PC)Y23\n" +
            "LPP)M6T\n" +
            "F82)9KL\n" +
            "9XR)VT4\n" +
            "SF1)4T3\n" +
            "FW6)N66\n" +
            "QBY)D49\n" +
            "BCM)17Y\n" +
            "H1W)R6K\n" +
            "ZVN)7QK\n" +
            "BRH)7JF\n" +
            "LKL)39C\n" +
            "LV1)BJS\n" +
            "8PC)FN6\n" +
            "CHB)TBS\n" +
            "ZLR)3XD\n" +
            "8BD)BSC\n" +
            "NVC)9FB\n" +
            "Z9L)HK1\n" +
            "FT3)BWL\n" +
            "446)S8V\n" +
            "LM1)D8G\n" +
            "KH3)Q6P\n" +
            "J8C)WFH\n" +
            "YT1)SDH\n" +
            "CGZ)X3V\n" +
            "77B)V9M\n" +
            "2RJ)H4V\n" +
            "NHY)H47\n" +
            "89B)HM7\n" +
            "Z1V)58S\n" +
            "17Y)1Q7\n" +
            "J3F)891\n" +
            "WDG)VSZ\n" +
            "PJM)21T\n" +
            "3YL)74D\n" +
            "8XJ)15N\n" +
            "Z2X)VHH\n" +
            "N6R)R93\n" +
            "5QV)8XY\n" +
            "KSD)RYF\n" +
            "6DQ)X8F\n" +
            "Z2Q)MZB\n" +
            "ZFG)972\n" +
            "5LK)FT3\n" +
            "D25)1CF\n" +
            "RMQ)2HQ\n" +
            "85N)HDY\n" +
            "952)WFS\n" +
            "T4J)B88\n" +
            "2MC)JFH\n" +
            "BRL)D64\n" +
            "GJ4)65N\n" +
            "ZC2)QLQ\n" +
            "69T)3WV\n" +
            "W4F)WMG\n" +
            "74D)NCN\n" +
            "3YY)19K\n" +
            "JKG)6CJ\n" +
            "S68)GGZ\n" +
            "6N6)H2P\n" +
            "3XL)ZVG\n" +
            "S1D)14K\n" +
            "GMK)DW3\n" +
            "HJF)1D5\n" +
            "9DP)P9D\n" +
            "18K)Z2Q\n" +
            "248)YD2\n" +
            "DTK)MR3\n" +
            "LH8)1GZ\n" +
            "7ZC)RZJ\n" +
            "YJ2)ZVN\n" +
            "JN1)1FX\n" +
            "3WV)289\n" +
            "53D)GJX\n" +
            "883)FXW\n" +
            "79K)ZXD\n" +
            "DLH)9X5\n" +
            "BRQ)KHK\n" +
            "2XW)R65\n" +
            "RGD)GCY\n" +
            "RNC)TR9\n" +
            "HYV)54C\n" +
            "SJF)BBD\n" +
            "T81)F2T\n" +
            "GZ2)KBQ\n" +
            "G2K)48L\n" +
            "PL6)B5D\n" +
            "R76)Z4Z\n" +
            "QVK)TDX\n" +
            "F6N)M6X\n" +
            "8XQ)3JP\n" +
            "HXD)WNB\n" +
            "CLZ)37R\n" +
            "K6R)SY1\n" +
            "X9G)8CM\n" +
            "2W9)W4X\n" +
            "ZXV)JC5\n" +
            "HKY)1Q4\n" +
            "KV1)QZC\n" +
            "LMT)CLW\n" +
            "Y4M)P57\n" +
            "1YS)SJF\n" +
            "NGV)N1R\n" +
            "VLF)RGD\n" +
            "FJ5)8WN\n" +
            "PWG)V4K\n" +
            "XDC)KY2\n" +
            "3DJ)RV8\n" +
            "1RJ)2GN\n" +
            "WXT)MP2\n" +
            "R89)JLR\n" +
            "GGB)RDG\n" +
            "Z6L)GQX\n" +
            "ZJQ)TLG\n" +
            "3WF)FQH\n" +
            "5YP)5Z3\n" +
            "C1B)CCD\n" +
            "SBW)BQB\n" +
            "41C)W4H\n" +
            "1P5)YYP\n" +
            "R5X)36J\n" +
            "DZL)KNW\n" +
            "P57)CN4\n" +
            "C85)78L\n" +
            "6YB)S7R\n" +
            "CYB)LNN\n" +
            "881)Z5X\n" +
            "642)B5K\n" +
            "X9J)SQT\n" +
            "BJK)M39\n" +
            "BMW)SHT\n" +
            "2NS)VKN\n" +
            "1C2)JHT\n" +
            "H46)ZGD\n" +
            "JY6)RF8\n" +
            "V1D)82Y\n" +
            "Z4Z)FW6\n" +
            "CRP)JRG\n" +
            "1VX)77V\n" +
            "M2F)MHH\n" +
            "B7X)JJV\n" +
            "H29)7JR\n" +
            "Z4C)N13\n" +
            "HN2)PRV\n" +
            "FTN)5FY\n" +
            "8HS)Z4M\n" +
            "JTP)GLS\n" +
            "JST)8XZ\n" +
            "4GX)T2P\n" +
            "1GZ)V8W\n" +
            "5MW)RT4\n" +
            "9G2)QPQ\n" +
            "X6C)NGV\n" +
            "GP8)8SY\n" +
            "J67)ZBL\n" +
            "R45)BWC\n" +
            "DDF)S37\n" +
            "31R)PHR\n" +
            "V4K)2L6\n" +
            "J69)SYP\n" +
            "DVF)R29\n" +
            "DLS)1BQ\n" +
            "72W)JKH\n" +
            "JPV)FL9\n" +
            "TSK)69T\n" +
            "93V)T9M\n" +
            "CST)WPW\n" +
            "37Y)BJ8\n" +
            "JR2)V4Z\n" +
            "B7C)X1V\n" +
            "WN7)GCD\n" +
            "K65)TM5\n" +
            "HFS)KYB\n" +
            "1XR)TX8\n" +
            "7L2)NXY\n" +
            "57Z)M6W\n" +
            "WMG)5HG\n" +
            "F6S)3YF\n" +
            "FMB)N6Q\n" +
            "HS4)QNV\n" +
            "XN6)X2C\n" +
            "56X)Z5F\n" +
            "NJ1)3M8\n" +
            "65K)S2S\n" +
            "MSJ)Z3P\n" +
            "3RW)YJQ\n" +
            "YRB)L4G\n" +
            "5DZ)5YP\n" +
            "TB6)TGV\n" +
            "PDM)H9F\n" +
            "MTR)B36\n" +
            "GGH)2LS\n" +
            "4S6)4KV\n" +
            "SVB)MV1\n" +
            "JQN)18K\n" +
            "SRN)ZFK\n" +
            "ZFX)HXD\n" +
            "YNR)GCL\n" +
            "8QM)GDK\n" +
            "17G)B9Y\n" +
            "JKZ)19N\n" +
            "MJD)5BH\n" +
            "NSR)24N\n" +
            "T48)CF2\n" +
            "Q3R)3TZ\n" +
            "741)T7M\n" +
            "P2C)G9Q\n" +
            "V8G)17G\n" +
            "GCC)54L\n" +
            "53K)TC8\n" +
            "ZGD)F7V\n" +
            "J5Z)Z7X\n" +
            "4YV)HZV\n" +
            "GPZ)69X\n" +
            "RYT)RTK\n" +
            "Z6T)7ZC\n" +
            "FMT)ZVJ\n" +
            "56X)7KS\n" +
            "M89)YDR\n" +
            "F6Q)V8G\n" +
            "Y4V)MY7\n" +
            "1Q7)17N\n" +
            "YV7)HQS\n" +
            "YLQ)GJ2\n" +
            "5WT)VQB\n" +
            "YN7)DR2\n" +
            "MPX)JBC\n" +
            "LFL)DPB\n" +
            "TNG)5Q1\n" +
            "LW7)HC8\n" +
            "HBR)Q6N\n" +
            "9K2)DNB\n" +
            "GXN)MHW\n" +
            "SGZ)1HF\n" +
            "WFS)N4R\n" +
            "3GN)2K4\n" +
            "5Y4)1MH\n" +
            "M9W)7PR\n" +
            "WCK)DMQ\n" +
            "COM)TKH\n" +
            "6XY)LTM\n" +
            "WQF)1S2\n" +
            "Z6N)3BD\n" +
            "CF2)LFL\n" +
            "GDX)ZQ4\n" +
            "PGZ)1VH\n" +
            "X5D)6CP\n" +
            "TDX)MKV\n" +
            "3XX)BHR\n" +
            "SPL)DXS\n" +
            "GM5)TZR\n" +
            "M8W)DBH\n" +
            "PFH)KGJ\n" +
            "W4H)MKN\n" +
            "SPK)LRQ\n" +
            "V4P)63V\n" +
            "5LQ)WDG\n" +
            "L2G)49J\n" +
            "HB2)6Q9\n" +
            "YV4)NTM\n" +
            "H47)9MW\n" +
            "ZB8)Y8J\n" +
            "C3D)HTQ\n" +
            "9HF)9K2\n" +
            "XDG)GDX\n" +
            "FMS)239\n" +
            "JJP)PKV\n" +
            "6C1)BL3\n" +
            "FNX)JX4\n" +
            "SN2)237\n" +
            "TSD)PNN\n" +
            "RY1)JL3\n" +
            "TX5)B2R\n" +
            "BS5)HJK\n" +
            "TBS)JNC\n" +
            "1BQ)PR5\n" +
            "NRS)FX1\n" +
            "5GX)BKC\n" +
            "8Y8)FRH\n" +
            "GP1)KFR\n" +
            "H1W)ZLJ\n" +
            "FX1)WT6\n" +
            "HJK)WFT\n" +
            "7Z4)GT9\n" +
            "FD8)RGG\n" +
            "8VZ)5PJ\n" +
            "1LW)PTY\n" +
            "PTT)15X\n" +
            "QVZ)6LR\n" +
            "Q9V)WMP\n" +
            "BLW)4DX\n" +
            "554)35D\n" +
            "YML)DND\n" +
            "997)CTW\n" +
            "L2L)6WB\n" +
            "PR9)K5K\n" +
            "6TY)5Y4\n" +
            "2RQ)DVF\n" +
            "5PL)NK7\n" +
            "3WB)KJ7\n" +
            "PXM)HN2\n" +
            "NBJ)FMB\n" +
            "BGN)BRP\n" +
            "BTH)C2B\n" +
            "9X5)MLT\n" +
            "XGJ)KGD\n" +
            "TDC)SBW\n" +
            "56Q)K7F\n" +
            "HF3)Z2X\n" +
            "RP9)952\n" +
            "PKV)K4K\n" +
            "222)95K\n" +
            "LX9)4WG\n" +
            "RYF)HB2\n" +
            "5CL)C4P\n" +
            "J2H)6PG\n" +
            "CXP)5GB\n" +
            "38R)L7N\n" +
            "NJ1)YDZ\n" +
            "LBC)42B\n" +
            "6WB)NCK\n" +
            "524)YOU\n" +
            "D8X)YNZ\n" +
            "KY2)BRH\n" +
            "W5X)DZX\n" +
            "SP9)G1J\n" +
            "JKT)LGJ\n" +
            "J2V)PJT\n" +
            "6SS)R9G\n" +
            "8MF)2L8\n" +
            "X4J)8JJ\n" +
            "T1P)DLS\n" +
            "NWC)76R\n" +
            "YXW)RMQ\n" +
            "Y64)9NF\n" +
            "XB5)52M\n" +
            "JKP)YC1\n" +
            "FZ2)ZCD\n" +
            "Q3S)CWT\n" +
            "YCS)QDR\n" +
            "S3M)792\n" +
            "Q7K)N5M\n" +
            "952)MYL\n" +
            "GPR)F37\n" +
            "Y7G)TFK\n" +
            "V7H)2G3\n" +
            "CHW)BVC\n" +
            "FSM)TRY\n" +
            "RS7)BFX\n" +
            "KF6)3RW\n" +
            "TGV)6BJ\n" +
            "3TP)CXP\n" +
            "DXS)BW8\n" +
            "8QM)NT3\n" +
            "R4Z)X43\n" +
            "7X3)7N7\n" +
            "JJZ)3WB\n" +
            "GWZ)K7Z\n" +
            "XQF)R1M\n" +
            "2L8)4YX\n" +
            "891)F1D\n" +
            "S73)KS9\n" +
            "289)3TB\n" +
            "XJF)PDZ\n" +
            "C29)K7N\n" +
            "YH5)8F3\n" +
            "9NF)8LD\n" +
            "YX7)1NW\n" +
            "ZLJ)ZGS\n" +
            "DWS)CY2\n" +
            "Z4P)XBM\n" +
            "HKY)K55\n" +
            "P6W)BWQ\n" +
            "P1H)L64\n" +
            "54T)25P\n" +
            "W38)6KP\n" +
            "CNV)9S2\n" +
            "7FS)75T\n" +
            "9SV)PQQ\n" +
            "H46)VL3\n" +
            "3FW)W91\n" +
            "JBW)T99\n" +
            "J89)MLR\n" +
            "CJC)4B6\n" +
            "NYK)189\n" +
            "R2K)3CT\n" +
            "S54)BHJ\n" +
            "98D)HRL\n" +
            "F1T)GRQ\n" +
            "T9M)NZJ\n" +
            "5B2)FNX\n" +
            "PQJ)D89\n" +
            "WG3)2W2\n" +
            "ZS9)WW8\n" +
            "FSG)5SS\n" +
            "DW4)ZFG\n" +
            "78L)49Z\n" +
            "NGQ)2TJ\n" +
            "M6X)GDP\n" +
            "KXR)95L\n" +
            "1WQ)FNT\n" +
            "BRP)L4X\n" +
            "J3F)5C4\n" +
            "2NB)JJD\n" +
            "SZL)5PT\n" +
            "FNB)DN9\n" +
            "LNZ)ZBG\n" +
            "Z4J)NQV\n" +
            "D6J)H54\n" +
            "1CF)SZF\n" +
            "QQF)1N2\n" +
            "FFS)VF9\n" +
            "NK7)KRM\n" +
            "6HY)TDQ\n" +
            "C2Q)16T\n" +
            "JTK)ZLR\n" +
            "1KD)N3R\n" +
            "2XH)JKP\n" +
            "BJ8)QHR\n" +
            "G9Y)5F2\n" +
            "4R7)HGM\n" +
            "JGH)XS7\n" +
            "72G)LLM\n" +
            "QLQ)Q1Y\n" +
            "TJL)8JW\n" +
            "N8F)8SX\n" +
            "JY8)HZD\n" +
            "3W9)JPV\n" +
            "WK4)HBD\n" +
            "8X9)6XH\n" +
            "YYG)WJQ\n" +
            "HZL)NQZ\n" +
            "BLY)JJG\n" +
            "6CH)CR4\n" +
            "GQ6)248\n" +
            "DWH)5LK\n" +
            "LQM)Z7Q\n" +
            "SN2)4DC\n" +
            "BF7)BTH\n" +
            "Z9S)NG8\n" +
            "F5D)HK4\n" +
            "2S6)5NW\n" +
            "LTM)757\n" +
            "FC8)89N\n" +
            "SBJ)4T4\n" +
            "XLM)XQR\n" +
            "S29)TDC\n" +
            "1YK)RL3\n" +
            "6J2)7NB\n" +
            "SK1)7CS\n" +
            "GBD)H77\n" +
            "9KL)HJF\n" +
            "LJ4)VST\n" +
            "S9W)4KN\n" +
            "99C)Z6N\n" +
            "L58)M2K\n" +
            "5JS)LR8\n" +
            "WR5)9XR\n" +
            "V6W)WK4\n" +
            "9S7)FRC\n" +
            "TM8)C39\n" +
            "F4Q)Y86\n" +
            "BN1)MTR\n" +
            "BGG)GP8\n" +
            "GJN)MV8\n" +
            "TLG)XYH\n" +
            "83S)CHW\n" +
            "Z1H)GX4\n" +
            "3TB)HHX\n" +
            "J3Q)JQL\n" +
            "5Q1)75N\n" +
            "W91)57T\n" +
            "DVJ)HBR\n" +
            "B6F)M9M\n" +
            "WMP)5XN\n" +
            "WXQ)B17\n" +
            "83M)XMH\n" +
            "8N9)SAN\n" +
            "LVG)8ZV\n" +
            "L2J)7SB\n" +
            "FNT)KM7\n" +
            "BPC)B9T\n" +
            "1TQ)K27\n" +
            "JZR)RJ4\n" +
            "L9S)H93\n" +
            "189)36D\n" +
            "TZG)2Z4\n" +
            "5LZ)HXM\n" +
            "SJD)Q3S\n" +
            "WJQ)D81\n" +
            "GP8)GZ2\n" +
            "1TP)ZNV\n" +
            "X2J)837\n" +
            "DJM)KDJ\n" +
            "7GP)NYK\n" +
            "TQ8)446\n" +
            "HZL)4L8\n" +
            "29G)3VP\n" +
            "4LZ)XTK\n" +
            "KFX)6N6\n" +
            "HPM)WWQ\n" +
            "X1V)KVV\n" +
            "Y64)V4C\n" +
            "5GN)54T\n" +
            "SJ1)QS3\n" +
            "DM4)83W\n" +
            "KDT)ZB8\n" +
            "DL7)DKC\n" +
            "TML)SPL\n" +
            "LC2)K1W\n" +
            "MHW)5Z7\n" +
            "MXT)RQN\n" +
            "9KL)K9L\n" +
            "M3T)YRM\n" +
            "KFR)Q49\n" +
            "1DJ)SN2\n" +
            "F82)2J1\n" +
            "PWN)5PX\n" +
            "YT1)V7F\n" +
            "T6S)T1F\n" +
            "B8L)WB2\n" +
            "Q79)LKF\n" +
            "853)RTD\n" +
            "KBQ)356\n" +
            "HTL)54G\n" +
            "43T)53D\n" +
            "B5W)PH9\n" +
            "7KQ)8TX\n" +
            "T2Z)1WQ\n" +
            "8HY)29M\n" +
            "552)M74\n" +
            "STR)6HX\n" +
            "FRV)HMM\n" +
            "45F)J7C\n" +
            "4Y9)HFS\n" +
            "GNN)WJ6\n" +
            "HXT)JQ8\n" +
            "PNN)51L\n" +
            "PHR)RK5\n" +
            "MM8)H1B\n" +
            "N66)G85\n" +
            "C4P)W7Z\n" +
            "991)FSM\n" +
            "7QK)SLP\n" +
            "GDP)71Q\n" +
            "5MC)MRG\n" +
            "F2X)HY1\n" +
            "B9B)CWM\n" +
            "SVZ)HN8\n" +
            "XDB)4P8\n" +
            "BS3)VFP\n" +
            "VXM)KCL\n" +
            "9G6)831\n" +
            "9Z8)FNJ\n" +
            "GX4)C2Q\n" +
            "WFB)MZ9\n" +
            "63V)MX3\n" +
            "V8W)82Z\n" +
            "RTK)319\n" +
            "427)WY1\n" +
            "4T3)VVN\n" +
            "T2P)4LC\n" +
            "CR4)FQS\n" +
            "K4L)DTK\n" +
            "HLP)WCK\n" +
            "4YQ)H9N\n" +
            "RK5)QFW\n" +
            "GT9)SRN\n" +
            "YXF)FXY\n" +
            "V74)L3W\n" +
            "MY7)2RQ\n" +
            "JLR)JNS\n" +
            "9S5)LPH\n" +
            "H54)J37\n" +
            "8XR)BLY\n" +
            "QMC)T48\n" +
            "4TY)1QG\n" +
            "Z4J)H82\n" +
            "BZC)LKD\n" +
            "4CP)86F\n" +
            "Z24)L58\n" +
            "1FN)X15\n" +
            "5FJ)QWJ\n" +
            "K27)2CD\n" +
            "3Z9)3W9\n" +
            "L6V)J1J\n" +
            "51V)HJ2\n" +
            "WD5)Q99\n" +
            "49Z)G6N\n" +
            "Y4V)DDF\n" +
            "MFV)3GH\n" +
            "B1T)9CM\n" +
            "X9Z)BG5\n" +
            "2M6)1XQ\n" +
            "2J8)3G5\n" +
            "VMB)13Z\n" +
            "51S)BMW\n" +
            "1MH)LFK\n" +
            "VBK)3D4\n" +
            "SDM)8XR\n" +
            "7NX)S2K\n" +
            "52L)4NL\n" +
            "LRS)664\n" +
            "JDD)43S\n" +
            "JJV)H6X\n" +
            "62K)7L2\n" +
            "WR1)L3D\n" +
            "LN4)WXQ\n" +
            "S52)C85\n" +
            "F22)9SV\n" +
            "LH3)8B2\n" +
            "YBD)8MY\n" +
            "TGM)N6H\n" +
            "ZVJ)MSN\n" +
            "S2S)5HV\n" +
            "2MF)GP1\n" +
            "9ZP)3ZK\n" +
            "1LW)H44\n" +
            "QTW)T9P\n" +
            "GHZ)YV7\n" +
            "W7Z)M3Y\n" +
            "5FK)NWC\n" +
            "97X)36T\n" +
            "G7X)K5R\n" +
            "GLP)XQF\n" +
            "WQH)ZM7\n" +
            "8YP)KF6\n" +
            "WNB)WG1\n" +
            "W21)1TQ\n" +
            "VBH)XM4\n" +
            "CY5)3N6\n" +
            "G1V)K1G\n" +
            "L2X)L9S\n" +
            "2CV)3LL\n" +
            "BKC)LC8\n" +
            "R5P)JDL\n" +
            "JL3)T5B\n" +
            "HDY)FRM\n" +
            "XL2)F29\n" +
            "8Y8)N86\n" +
            "C8B)FDF\n" +
            "L3W)Z9L\n" +
            "WJ6)6FW\n" +
            "5HV)157\n" +
            "DW9)1WX\n" +
            "C2B)JR2\n" +
            "6HK)7GP\n" +
            "N86)971\n" +
            "GZ6)KHJ\n" +
            "V4Z)376\n" +
            "WT6)F4Q\n" +
            "H97)FP5\n" +
            "M4L)MCT\n" +
            "D8G)BCQ\n" +
            "XPG)NP5\n" +
            "8CG)GBD\n" +
            "6SD)6X3\n" +
            "54L)1TP\n" +
            "N1W)MJD\n" +
            "ZXT)VXM\n" +
            "QH7)JN5\n" +
            "S7H)4M5\n" +
            "QSC)44B\n" +
            "19K)QLJ\n" +
            "951)25C\n" +
            "PJZ)W21\n" +
            "X8F)X4F\n" +
            "CZW)SV8\n" +
            "ZYJ)F5C\n" +
            "XNR)KPH\n" +
            "658)47Q\n" +
            "D66)3GD\n" +
            "ZGK)D65\n" +
            "4ZT)YBT\n" +
            "3NR)K3P\n" +
            "WMD)HRP\n" +
            "VGN)554\n" +
            "2GN)WH3\n" +
            "8SX)DXJ\n" +
            "Z4M)MR9\n" +
            "R1V)VDY\n" +
            "1D1)CRZ\n" +
            "CC5)MH1\n" +
            "2NS)PXH\n" +
            "SLP)1FN\n" +
            "PTB)LYC\n" +
            "V4D)Z5M\n" +
            "Z2N)X77\n" +
            "DR4)7KQ\n" +
            "646)98D\n" +
            "9PN)F21\n" +
            "PB8)728\n" +
            "WXT)4S9\n" +
            "3YP)TGM\n" +
            "6PG)776\n" +
            "9KY)T7C\n" +
            "5SS)LV1\n" +
            "8HR)53Z\n" +
            "972)FZ2\n" +
            "XJ8)9PN\n" +
            "6PB)Q35\n" +
            "ZCR)42N\n" +
            "NNP)YPG\n" +
            "SL6)XL4\n" +
            "1CG)YZJ\n" +
            "QKG)5GX\n" +
            "L94)HD8\n" +
            "ZVH)GVJ\n" +
            "R93)3YL\n" +
            "4GC)2XH\n" +
            "FNJ)ZL5\n" +
            "2LR)YBD\n" +
            "YDW)HMN\n" +
            "S8V)YRB\n" +
            "YV2)HS4\n" +
            "6B6)6WZ\n" +
            "SVG)LB5\n" +
            "DMQ)VWX\n" +
            "72Y)997\n" +
            "MHY)3YY\n" +
            "JX9)XHT\n" +
            "MTV)DSB\n" +
            "413)6SD\n" +
            "DSB)25Q\n" +
            "9HF)BRG\n" +
            "B5W)P93\n" +
            "9TB)XTP\n" +
            "JN3)6W2\n" +
            "TFK)MKW\n" +
            "T49)4NY\n" +
            "742)MSJ\n" +
            "8F6)ZKW\n" +
            "TRQ)3JD\n" +
            "F2T)R8H\n" +
            "LQ4)GMJ\n" +
            "B9T)H46\n" +
            "T2F)ZC2\n" +
            "VC6)TJF\n" +
            "YDZ)R48\n" +
            "RGG)974\n" +
            "DTK)H4C\n" +
            "DTF)QCP\n" +
            "7KM)Z4C\n" +
            "GTS)MLJ\n" +
            "296)424\n" +
            "664)H86\n" +
            "2YP)ZYJ\n" +
            "V18)VC6\n" +
            "7CS)SQH\n" +
            "DZS)3X8\n" +
            "QYT)8HS\n" +
            "62Y)SQW\n" +
            "D8X)YXX\n" +
            "N2X)D3B\n" +
            "P84)6J2\n" +
            "JPH)DZL\n" +
            "WM9)KWM\n" +
            "TM5)GM5\n" +
            "W4X)YYR\n" +
            "TNG)LRP\n" +
            "1KP)ZQX\n" +
            "MZ9)72Y\n" +
            "WJZ)MPF\n" +
            "NP5)SQ3\n" +
            "D66)5QS\n" +
            "H7H)ZCB\n" +
            "16T)V74\n" +
            "X15)1WS\n" +
            "8NR)Y7N\n" +
            "237)DYP\n" +
            "N4Y)CGZ\n" +
            "Z8K)BYX\n" +
            "8KF)N6W\n" +
            "RF8)NMV\n" +
            "WFC)7XF\n" +
            "449)DDB\n" +
            "D49)X1H\n" +
            "TM8)78Q\n" +
            "G6N)73R\n" +
            "HGM)GD7\n" +
            "F21)Y1R\n" +
            "TRC)5HH\n" +
            "N14)S73\n" +
            "ZXT)BS5\n" +
            "NG8)4L5\n" +
            "8ZN)Q79\n" +
            "4HJ)Q3T\n" +
            "837)NDT\n" +
            "1R7)R2K\n" +
            "77S)6YB\n" +
            "S7R)1XY\n" +
            "2VT)KNJ\n" +
            "WQ4)64D\n" +
            "M5Z)PVZ\n" +
            "RQN)8V9\n" +
            "VVN)K2K\n" +
            "V2B)N3K\n" +
            "B17)7BX\n" +
            "1W5)LMT\n" +
            "1YW)X2J\n" +
            "XJC)XJF\n" +
            "P4W)4J1\n" +
            "PRS)Q4P\n" +
            "BMM)QB5\n" +
            "L7N)H29\n" +
            "4W5)GKS\n" +
            "8WN)KH8\n" +
            "N4R)39M\n" +
            "4NY)14W\n" +
            "19Q)ZG9\n" +
            "W6W)J8C\n" +
            "PWZ)4RW\n" +
            "8F3)JBW\n" +
            "BC8)F4N\n" +
            "QG8)VDP\n" +
            "YG1)GBY\n" +
            "KRM)WJZ\n" +
            "4HL)2TH\n" +
            "W1V)FMT\n" +
            "1BL)NC2\n" +
            "RTN)R6C\n" +
            "QLJ)PLT\n" +
            "SQH)93Y\n" +
            "KM7)9G2\n" +
            "5Z3)JY8\n" +
            "WB2)YSP\n" +
            "3S1)4W5\n" +
            "5BH)SXV\n" +
            "28Q)5Q7\n" +
            "PDZ)XD1\n" +
            "D79)WHF\n" +
            "6BJ)DQT\n" +
            "5F8)C29\n" +
            "46R)XNR\n" +
            "NC2)2Y8\n" +
            "T5B)863\n" +
            "TJF)PDM\n" +
            "L47)5QW\n" +
            "F59)JX9\n" +
            "RK6)QG8\n" +
            "GD7)RWP\n" +
            "863)7DK\n" +
            "97R)LJF\n" +
            "6N7)X32\n" +
            "WLZ)XDM\n" +
            "RXH)79K\n" +
            "WG1)NQW\n" +
            "BNR)1P5\n" +
            "ZXV)QQF\n" +
            "ZJX)GSZ\n" +
            "X2C)L5L\n" +
            "NVC)L2G\n" +
            "T1F)FK2\n" +
            "GGZ)KH3\n" +
            "TZC)R9K\n" +
            "157)FRV\n" +
            "3CX)Z1J\n" +
            "NS1)BGG\n" +
            "MFW)36X\n" +
            "DW3)C53\n" +
            "88H)LP4\n" +
            "FX4)F4M\n" +
            "676)7BB\n" +
            "9TR)Q3H\n" +
            "P5H)Z1H\n" +
            "LB1)XBR\n" +
            "SWS)FLP\n" +
            "4S4)QMC\n" +
            "KNW)5LZ\n" +
            "3PR)TVL\n" +
            "JYK)46F\n" +
            "ZM7)Z6T\n" +
            "Q99)427\n" +
            "5R1)MYP\n" +
            "3TZ)YHB\n" +
            "QPD)L6V\n" +
            "HB8)K7P\n" +
            "2W2)ZFX\n" +
            "BS3)GWH\n" +
            "953)S2C\n" +
            "1BC)WKC\n" +
            "S7X)9PL\n" +
            "1RQ)KLD\n" +
            "1XY)JRV\n" +
            "D37)SF5\n" +
            "PXD)P2C\n" +
            "4L4)CVV\n" +
            "MYP)2VZ\n" +
            "WPW)SFQ\n" +
            "N6H)8D7\n" +
            "8B7)9RM\n" +
            "297)Q93\n" +
            "LNG)R64\n" +
            "BXB)NSR\n" +
            "DKC)MTV\n" +
            "6C1)81V\n" +
            "75N)21C\n" +
            "XY7)THS\n" +
            "BRG)YY2\n" +
            "F37)RMV\n" +
            "831)LYP\n" +
            "M1P)GZ6\n" +
            "ZXD)NR9\n" +
            "6G1)35R\n" +
            "H2V)51V\n" +
            "Q9F)RRD\n" +
            "FXW)3XX\n" +
            "ZV3)CDP\n" +
            "JC5)JGH\n" +
            "Y73)KFX\n" +
            "V6G)1W5\n" +
            "7BB)DR7\n" +
            "RN7)56M\n" +
            "3GV)8X9\n" +
            "HMM)41C\n" +
            "JK4)V1D\n" +
            "MFV)2J4\n" +
            "QQW)H62\n" +
            "N1R)CCC\n" +
            "B5T)3GV\n" +
            "G8D)8QM\n" +
            "JNB)Z75\n" +
            "8D7)ST5\n" +
            "JXX)C1B\n" +
            "G5Y)Y92\n" +
            "G46)DW4\n" +
            "3CQ)R9L\n" +
            "FR9)Q83\n" +
            "N6Q)JR4\n" +
            "ZG2)S4Z\n" +
            "JDC)NCF\n" +
            "ZLX)2XW\n" +
            "JJD)QLN\n" +
            "YY2)FJ5\n" +
            "Z3P)W7C\n" +
            "LSB)N68\n" +
            "64D)8BL\n" +
            "PR9)J67\n" +
            "N6X)M2F\n" +
            "SQ3)XZ7\n" +
            "MKW)KVM\n" +
            "L61)PL4\n" +
            "R2Z)2BF\n" +
            "HGM)KQK\n" +
            "222)RJQ\n" +
            "4LC)PY4\n" +
            "54C)N14\n" +
            "MLR)Z7Z\n" +
            "BBD)W1V\n" +
            "JK1)32M\n" +
            "SY1)3S1\n" +
            "65N)3TK\n" +
            "1X9)4HQ\n" +
            "6F3)H6H\n" +
            "489)GFB\n" +
            "Y86)52L\n" +
            "HN7)R1G\n" +
            "48K)5MC\n" +
            "4P3)Z6L\n" +
            "CHT)8R9\n" +
            "3M8)HKP\n" +
            "RK6)PP4\n" +
            "X77)V4D\n" +
            "YDR)LCG\n" +
            "DZP)3CY\n" +
            "75T)TKM\n" +
            "ZFK)5LQ\n" +
            "6R6)8NV\n" +
            "TVL)RHW\n" +
            "HMN)BNR\n" +
            "PG2)VN1\n" +
            "FVQ)SQ5\n" +
            "1HF)W5X\n" +
            "WVY)TGX\n" +
            "VYF)2N1\n" +
            "BJS)LTJ\n" +
            "72V)GCC\n" +
            "8NV)BS3\n" +
            "ZL5)P1H\n" +
            "3KR)69D\n" +
            "CZS)8WW\n" +
            "4N2)72G\n" +
            "KK2)JXX\n" +
            "5Q7)KPZ\n" +
            "4QP)HYV\n" +
            "1SY)V7H\n" +
            "CN4)JTP\n" +
            "9TC)SVG\n" +
            "K7P)T6S\n" +
            "QFQ)999\n" +
            "NGN)QKG\n" +
            "BHR)DR4\n" +
            "TGX)XPG\n" +
            "DY3)YG1\n" +
            "M5Z)PHZ\n" +
            "KBQ)HVY\n" +
            "9D2)N5J\n" +
            "GMF)4LZ\n" +
            "1P8)BFN\n" +
            "GBY)KY4\n" +
            "49M)LWB\n" +
            "FNZ)FFS\n" +
            "JL3)V2H\n" +
            "LB5)7FK\n" +
            "PM5)1BL\n" +
            "PHZ)LH8\n" +
            "NCF)YNR\n" +
            "HSK)W6W\n" +
            "5RJ)C95\n" +
            "RPK)ZRK\n" +
            "Y34)54N\n" +
            "5QW)TZ5\n" +
            "KGJ)43X\n" +
            "P2V)Q9T\n" +
            "NQZ)L7W\n" +
            "WP4)S29\n" +
            "J3S)C9G\n" +
            "5C2)TX5\n" +
            "3PM)PK2\n" +
            "3GD)393\n" +
            "CCD)3Z9\n" +
            "QKQ)PB8\n" +
            "FCN)LRS\n" +
            "FQ4)M3T\n" +
            "45B)B1T\n" +
            "NPJ)MK3\n" +
            "KGD)JJP\n" +
            "F5Y)JKZ\n" +
            "C6D)HSK\n" +
            "TR9)7SS\n" +
            "2TX)H73\n" +
            "NFV)X5D\n" +
            "C2V)43T\n" +
            "M6T)KPS\n" +
            "PK2)1CG\n" +
            "TP1)N4Y\n" +
            "1D5)D9Z\n" +
            "MTR)97R\n" +
            "3TK)X3W\n" +
            "R7T)3VC\n" +
            "PHP)1LV\n" +
            "5GB)2H5\n" +
            "YC1)24X\n" +
            "S5H)W79\n" +
            "FQS)JVF\n" +
            "DML)6F3\n" +
            "Z75)LXP\n" +
            "DMJ)29G\n" +
            "54N)GSS\n" +
            "RWP)D79\n" +
            "VBV)XWX\n" +
            "VST)CMS\n" +
            "GZ2)676\n" +
            "N72)FP3\n" +
            "792)ZJX\n" +
            "H73)J17\n" +
            "M8N)WQ4\n" +
            "H6X)L5G\n" +
            "3VC)LBC\n" +
            "YBT)YR2\n" +
            "LYC)4GX\n" +
            "3VP)17F\n" +
            "F5Y)9ZY\n" +
            "8LD)BCM\n" +
            "7JR)X45\n" +
            "MV8)FY7\n" +
            "JN6)31R\n" +
            "MZ5)CVK\n" +
            "239)S7Y\n" +
            "DJ3)S7H\n" +
            "RVK)6HK\n" +
            "G85)WR5\n" +
            "LKF)TZG\n" +
            "SQ5)NP4\n" +
            "HN8)H53\n" +
            "CTW)MCJ\n" +
            "8ZV)6YF\n" +
            "2RQ)SR3\n" +
            "MRR)Z4P\n" +
            "WQ3)TYW\n" +
            "6SW)L2J\n" +
            "HFC)CTH\n" +
            "N5M)1TK\n" +
            "757)RDF\n" +
            "R5Z)MHY\n" +
            "NW9)V3P\n" +
            "K3P)PWN\n" +
            "GD7)GDL\n" +
            "B2J)FN2\n" +
            "BRJ)GK8\n" +
            "S62)3NT\n" +
            "9BH)38R\n" +
            "KQK)WXW\n" +
            "2LS)T8V\n" +
            "4J1)5WT\n" +
            "7J5)H3D\n" +
            "W1B)F72\n" +
            "F4N)NFK\n" +
            "QCP)4HJ\n" +
            "DWH)V5B\n" +
            "87N)XY7\n" +
            "F13)LWC\n" +
            "7VH)67W\n" +
            "PMG)DY4\n" +
            "JMC)WQ3\n" +
            "6HY)PTT\n" +
            "YJ8)DML\n" +
            "9CM)DM1\n" +
            "54J)DNJ\n" +
            "1Q6)8ST\n" +
            "CKW)XS3\n" +
            "ZKW)JPL\n" +
            "111)YFN\n" +
            "H6W)R5Z\n" +
            "THS)X4J\n" +
            "DTM)PWZ\n" +
            "ZH5)8PG\n" +
            "JR4)Z24\n" +
            "NCN)8HF\n" +
            "3BD)B8L\n" +
            "76R)LN4\n" +
            "N3K)97M\n" +
            "JJG)N1H\n" +
            "5JW)P48\n" +
            "YJS)XMP\n" +
            "4RW)T2Z\n" +
            "D65)DNY\n" +
            "KWM)ZGK\n" +
            "5FY)9BK\n" +
            "Y8J)7DR\n" +
            "5PJ)1YW\n" +
            "24L)PTB\n" +
            "XTR)PJZ\n" +
            "LLM)QSC\n" +
            "R6Z)V6W\n" +
            "H62)PQJ\n" +
            "HT7)V18\n" +
            "6CP)S3M\n" +
            "WXW)N6J\n" +
            "GJX)F5Y\n" +
            "Q35)QY7\n" +
            "3K8)F59\n" +
            "8SX)SWS\n" +
            "B2R)6N7\n" +
            "R8H)CRP\n" +
            "CGH)HFC\n" +
            "NWC)QKQ\n" +
            "P9D)BLW\n" +
            "NK3)YLD\n" +
            "CDP)2M4\n" +
            "Q39)QB9\n" +
            "F2J)X7D\n" +
            "J79)QHD\n" +
            "VXM)948\n" +
            "X7D)GLP\n" +
            "NP4)Q37\n" +
            "69H)K1C\n" +
            "FF1)65K\n" +
            "P7X)YDW\n" +
            "HTK)B6F\n" +
            "273)CTT\n" +
            "D25)164\n" +
            "QGY)DXG\n" +
            "G46)BMM\n" +
            "QPQ)SZL\n" +
            "HM7)G7X\n" +
            "VMJ)J24\n" +
            "5QS)RD6\n" +
            "KVV)4CP\n" +
            "6W2)8KQ\n" +
            "1JP)PR9\n" +
            "4B2)SF1\n" +
            "FX4)NNP\n" +
            "2N7)ZRC\n" +
            "JQ8)N1W\n" +
            "LKD)83V\n" +
            "345)CJC\n" +
            "HVF)QYT\n" +
            "Y4H)7VH\n" +
            "5LR)4MJ\n" +
            "S2C)FSG\n" +
            "V5B)BBN\n" +
            "5X5)SJ1\n" +
            "MKC)NPJ\n" +
            "BWL)F39\n" +
            "VDZ)Z27\n" +
            "7GP)YB3\n" +
            "8R9)R3N\n" +
            "SQW)GNG\n" +
            "3X8)V2B\n" +
            "D89)SM1\n" +
            "Z4P)RSN\n" +
            "YB3)5LR\n" +
            "V4C)1JP\n" +
            "FGH)FF1\n" +
            "GKS)R69\n" +
            "M5V)H4X\n" +
            "3CY)KXM\n" +
            "G4S)D5H\n" +
            "12P)1YK\n" +
            "3Y2)R1V\n" +
            "KTZ)DQW\n" +
            "KD3)L2L\n" +
            "KSL)F13\n" +
            "R3Z)JKT\n" +
            "G9Q)1D1\n" +
            "2J4)5DZ\n" +
            "X3V)MM8\n" +
            "Z7Y)1BC\n" +
            "G1J)G4S\n" +
            "W4X)LFX\n" +
            "YJ6)JMV\n" +
            "FP5)KN7\n" +
            "PCQ)8HR\n" +
            "FN2)W8G\n" +
            "31P)WFB\n" +
            "YXX)CYB\n" +
            "NXY)77B\n" +
            "NCK)Z8K\n" +
            "VPX)3TG\n" +
            "CN3)JY5\n" +
            "HXS)WQF\n" +
            "FK3)DZS\n" +
            "WFT)9DP\n" +
            "XZ5)F1L\n" +
            "639)T81\n" +
            "R26)PCQ\n" +
            "2VZ)YYD\n" +
            "4S9)1PZ\n" +
            "HVY)V4P\n" +
            "K55)K8N\n" +
            "2Y8)WMD\n" +
            "69T)24L\n" +
            "MHH)SRP\n" +
            "WPS)YWV\n" +
            "9PL)NHB\n" +
            "D3B)KDT\n" +
            "SHT)GJN\n" +
            "42N)6MG\n" +
            "K9F)YDT\n" +
            "N2R)FVQ\n" +
            "F3Q)296\n" +
            "YML)8XQ\n" +
            "6YF)B9B\n" +
            "R13)Y64\n" +
            "DNJ)DKW\n" +
            "H44)ZTP\n" +
            "1Q4)5JW\n" +
            "RLM)BRJ\n" +
            "LMJ)8HY\n" +
            "CL4)LF1\n" +
            "6GW)TMM\n" +
            "VTP)JWQ\n" +
            "TQL)G52\n" +
            "3QN)VWR\n" +
            "BFN)VPX\n" +
            "T39)TSK\n" +
            "Z1J)S3R\n" +
            "F7V)XBX\n" +
            "VNC)LW7\n" +
            "WM8)788\n" +
            "HBD)K9F\n" +
            "JQL)JGJ\n" +
            "3SV)WVN\n" +
            "DM1)297\n" +
            "VHQ)467\n" +
            "PVJ)12P\n" +
            "3GH)2M6\n" +
            "6MG)KD3\n" +
            "1NW)4GC\n" +
            "VTJ)FKC\n" +
            "Q8H)P86\n" +
            "5QW)BXB\n" +
            "ML7)V61\n" +
            "94V)NK3\n" +
            "XM4)TML\n" +
            "V2P)5Y3\n" +
            "CR6)JKG\n" +
            "7LG)S9W\n" +
            "8TX)V6G\n" +
            "2JY)ZG2\n" +
            "DVR)57Z\n" +
            "VN1)Z2R\n" +
            "ZC3)N2C\n" +
            "SB6)RPW\n" +
            "58W)1ZX\n" +
            "VFP)X6C\n" +
            "JQN)ZC3\n" +
            "53Z)LQM\n" +
            "KWL)TP1\n" +
            "HKP)4BW\n" +
            "S9T)Q19\n" +
            "K2K)WD5\n" +
            "WLM)YV4\n" +
            "SFQ)4R1\n" +
            "6KP)CTQ\n" +
            "V3P)XDC\n" +
            "CXM)MKC\n" +
            "31Y)Z62\n" +
            "XHT)L7R\n" +
            "FK2)S52\n" +
            "LVY)HFP\n" +
            "RJQ)KV1\n" +
            "9S2)2LR\n" +
            "NZ8)DVR\n" +
            "JKH)PG2\n" +
            "ZQX)3TP\n" +
            "81V)9CP\n" +
            "42B)WDJ\n" +
            "7PB)S68\n" +
            "39C)6C1\n" +
            "RR8)KSZ\n" +
            "XL4)RTN\n" +
            "3XH)RYQ\n" +
            "78Q)TP3\n" +
            "GCD)5YQ\n" +
            "R29)LVG\n" +
            "Q3H)646\n" +
            "TMM)ZLX\n" +
            "4B2)WDB\n" +
            "6N5)449\n" +
            "3XL)NFV\n" +
            "CDL)6JS\n" +
            "TMC)B7C\n" +
            "R1W)ZWC\n" +
            "LH3)XJC\n" +
            "CHH)DFJ\n" +
            "1FN)MLQ\n" +
            "LMT)658\n" +
            "HK8)BN1\n" +
            "73R)1GP\n" +
            "ZQ6)6B4\n" +
            "Z5X)D37\n" +
            "YPG)GTK\n" +
            "8SM)VL6\n" +
            "W5C)C6D\n" +
            "4BW)YS6\n" +
            "DYP)2TX\n" +
            "R9K)BRN\n" +
            "KS9)L9J\n" +
            "XTJ)B25\n" +
            "Y23)CHB\n" +
            "NHB)LG4\n" +
            "L5L)7Z4\n" +
            "DRK)9SL\n" +
            "ST5)NVC\n" +
            "2WH)DTM\n" +
            "1LV)SDM\n" +
            "788)256\n" +
            "TW7)6TN\n" +
            "6FW)3CX\n" +
            "BG9)4Y9\n" +
            "67W)JJ7\n" +
            "2D4)FR9\n" +
            "Z8K)F1J\n" +
            "LTJ)31P\n" +
            "R94)YJ8\n" +
            "5PT)MPX\n" +
            "9SL)LGR\n" +
            "FKZ)9G6\n" +
            "DR7)SGZ\n" +
            "SM7)9KY\n" +
            "TKH)8MF\n" +
            "VXB)4N2\n" +
            "XQR)W38\n" +
            "21F)HK8\n" +
            "Y3H)XLM\n" +
            "DBW)M8W\n" +
            "11H)853\n" +
            "1WS)66W\n" +
            "DW4)KNK\n" +
            "NQV)SVB\n" +
            "6ZZ)8YP\n" +
            "ZWC)5PL\n" +
            "PP4)3CQ\n" +
            "T8V)THM\n" +
            "J1J)HMK\n" +
            "CPB)Y7G\n" +
            "GYH)9BH\n" +
            "WPK)FMS\n" +
            "95D)FJW\n" +
            "HM7)CJJ\n" +
            "ZGS)LBV\n" +
            "HMK)BZC\n" +
            "2BF)DWS\n" +
            "LWC)85N\n" +
            "L3B)M1P\n" +
            "7C2)WG3\n" +
            "3ZK)7BM\n" +
            "GDK)8XJ\n" +
            "LGJ)4R6\n" +
            "DL1)JSJ\n" +
            "44B)6T9\n" +
            "KFT)CXM\n" +
            "Q4P)STR\n" +
            "LBC)6ZD\n" +
            "GDK)STH\n" +
            "6MX)F2P\n" +
            "Y92)21F\n" +
            "6ZD)YYQ\n" +
            "HYK)58W\n" +
            "3YF)KNM\n" +
            "X9G)8K2\n" +
            "QWN)JQN\n" +
            "17F)KTZ\n" +
            "CJ4)62Y\n" +
            "KQW)GMF\n" +
            "15N)S9T\n" +
            "G1V)GMK\n" +
            "M62)X6J\n" +
            "8V9)SVZ\n" +
            "WW8)DJ9\n" +
            "FP3)28Q\n" +
            "PMX)F3Q\n" +
            "N3G)56Q\n" +
            "46F)ZN3\n" +
            "D3M)S3P\n" +
            "D64)LVY\n" +
            "72Y)ZHM\n" +
            "LPH)WLM\n" +
            "HY1)HZL\n" +
            "L3D)QPD\n" +
            "Q9T)X6Z\n" +
            "6HG)3DJ\n" +
            "KBP)9TR\n" +
            "25C)9Z8\n" +
            "ZR9)RYK\n" +
            "TJR)5C2\n" +
            "56M)X4Y\n" +
            "TL2)5CL\n" +
            "939)ZVH\n" +
            "595)DTF\n" +
            "Z27)D25\n" +
            "54T)MWM\n" +
            "ZBL)W4F\n" +
            "6JS)H7H\n" +
            "YWV)QWN\n" +
            "5D9)S5H\n" +
            "P96)KZ1\n" +
            "TDQ)8JZ\n" +
            "NQW)VHQ\n" +
            "K9L)DMJ\n" +
            "H6W)8F6\n" +
            "2TJ)8NJ\n" +
            "MCJ)T1P\n" +
            "M94)JNB\n" +
            "5ZJ)9BG\n" +
            "KCL)RS7\n" +
            "X6J)ZGQ\n" +
            "PQQ)JN6\n" +
            "S2K)5FK\n" +
            "K7N)X2Q\n" +
            "HTQ)GW4\n" +
            "LTJ)RPK\n" +
            "DD2)8J5\n" +
            "7NX)Z2N\n" +
            "6LR)R3D\n" +
            "YR2)7Y7\n" +
            "JBS)CZW\n" +
            "ZRK)XJ8\n" +
            "4L5)3XF\n" +
            "GJ2)FNZ\n" +
            "XTP)YCS\n" +
            "HRP)P5H\n" +
            "BRJ)J89\n" +
            "RD6)ZR3\n" +
            "YNZ)N8F\n" +
            "2N1)XGH\n" +
            "JDL)DLD\n" +
            "YLD)94B\n" +
            "ZNV)1Q6\n" +
            "6TG)CR6\n" +
            "GMW)KWL\n" +
            "TZR)698\n" +
            "RDG)VGN\n" +
            "F1D)5X5\n" +
            "3CT)6CH\n";

    private static int answer = 0;
    private static Map<String, List<String>> adjacencyList;

    private static final String ROOT = "COM";
    private static final String START = "YOU";
    private static final String DESTINATION = "SAN";

    public static void solve() {
        parseInput();
        answer = 0;

        traverseTree(ROOT, 0, "");

        System.out.println("Answer: " + answer); // 453028
    }

    public static void solvePart2() {
//        input = "COM)B\n" +
//                "B)C\n" +
//                "C)D\n" +
//                "D)E\n" +
//                "E)F\n" +
//                "B)G\n" +
//                "G)H\n" +
//                "D)I\n" +
//                "E)J\n" +
//                "J)K\n" +
//                "K)L\n" +
//                "K)YOU\n" +
//                "I)SAN"; // Answer: 4
        parseInput();
        answer = Integer.MAX_VALUE;

        findInTree(START, -1, "");

        System.out.println("Answer: " + answer); // 562
    }

    private static void findInTree(String currentNode, int currentLevel, String comingFrom) {
        if (!adjacencyList.containsKey(currentNode)) {
            return;
        }
        List<String> neighbours = adjacencyList.get(currentNode).stream()
                .filter(neighbour -> !neighbour.equals(comingFrom)) // Dont go back to where you came from
                .collect(Collectors.toList());

        if (neighbours.stream().anyMatch(neighbour -> neighbour.equals(DESTINATION))) {
            answer = Math.min(answer, currentLevel);
            return;
        }

        neighbours.forEach(neighbour -> findInTree(neighbour, currentLevel + 1, currentNode));
    }

    private static void traverseTree(String currentNode, int currentLevel, String comingFrom) {
        answer += currentLevel;
        if (!adjacencyList.containsKey(currentNode)) {
            return;
        }
        List<String> neighbours = adjacencyList.get(currentNode).stream()
                .filter(neighbour -> !neighbour.equals(comingFrom)) // Dont go back to where you came from
                .collect(Collectors.toList());
        neighbours.forEach(neighbour -> traverseTree(neighbour, currentLevel + 1, currentNode));
    }


    private static void parseInput() {
        adjacencyList = new HashMap<>();

        String[] links = input.split("\n");
        for (String link : links) {
            String[] bodies = link.split("\\)");
            adjacencyList.putIfAbsent(bodies[0], new ArrayList<>());
            adjacencyList.get(bodies[0]).add(bodies[1]);

            adjacencyList.putIfAbsent(bodies[1], new ArrayList<>());
            adjacencyList.get(bodies[1]).add(bodies[0]);
        }
    }
}
